package model;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.id
     *
     * @mbggenerated Wed Aug 10 01:10:11 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.stu_name
     *
     * @mbggenerated Wed Aug 10 01:10:11 CST 2016
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.class_name
     *
     * @mbggenerated Wed Aug 10 01:10:11 CST 2016
     */
    private String className;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.id
     *
     * @return the value of Student.id
     *
     * @mbggenerated Wed Aug 10 01:10:11 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.id
     *
     * @param id the value for Student.id
     *
     * @mbggenerated Wed Aug 10 01:10:11 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.stu_name
     *
     * @return the value of Student.stu_name
     *
     * @mbggenerated Wed Aug 10 01:10:11 CST 2016
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.stu_name
     *
     * @param stuName the value for Student.stu_name
     *
     * @mbggenerated Wed Aug 10 01:10:11 CST 2016
     */
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.class_name
     *
     * @return the value of Student.class_name
     *
     * @mbggenerated Wed Aug 10 01:10:11 CST 2016
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.class_name
     *
     * @param className the value for Student.class_name
     *
     * @mbggenerated Wed Aug 10 01:10:11 CST 2016
     */
    public void setClassName(String className) {
        this.className = className;
    }
}